## Inversão {#matrices-inversion}

Uma matriz quadrada $\mathbf{A}$ é inversível (ou não singular) se $\det(\mathbf{A}) \neq 0$. Matrizes não inversíveis também são conhecidas como matrizes singulares.

Por exemplo, dada a matriz $\mathbf{A}$,

$$
\mathbf{A} = \begin{bmatrix}
1 & 3 \\ 
2 & 7
\end{bmatrix} \text{,}
$$
observa-se que $\det(\mathbf{A}) = 7 - 6 = 1$, conforme visto em \@ref(matrices-det). Portanto, conclui-se que $\mathbf{A}$ é uma matriz inversível.

Como $\mathbf{A}$ é inversível, então existe uma única matriz $\mathbf{A}^{-1}$ tal que $\mathbf{A}\mathbf{A}^{-1} = \mathbf{A}^{-1}\mathbf{A} = \mathbf{I}$. Portanto,

$$
\begin{bmatrix}
1 & 3 \\ 
2 & 7
\end{bmatrix}\begin{bmatrix}
a'_{11} & a'_{12} \\ 
a'_{21} & a'_{22}
\end{bmatrix} = \begin{bmatrix}
1 & 0 \\ 
0 & 1
\end{bmatrix} \text{.}
$$
Calculando o produto $\mathbf{AA}^{-1}$, conforme visto em \@ref(matrices-operations-matmul), obtem-se:

$$
\begin{bmatrix}
1 & 3 \\ 
2 & 7
\end{bmatrix}\begin{bmatrix}
a'_{11} & a'_{12} \\ 
a'_{21} & a'_{22}
\end{bmatrix} = \begin{bmatrix}
1a'_{11} + 3a'_{21} & 1a'_{12} + 3a'_{22}\\ 
2a'_{11} + 7a'_{21} & 2a'_{12} + 7a'_{22} 
\end{bmatrix} \text{.}
$$
Logo,

$$
\begin{bmatrix}
1a'_{11} + 3a'_{21} & 1a'_{12} + 3a'_{22}\\ 
2a'_{11} + 7a'_{21} & 2a'_{12} + 7a'_{22} 
\end{bmatrix} = \begin{bmatrix}
1 & 0 \\ 
0 & 1
\end{bmatrix} \text{.}
$$
Por definição de igualdade de matrizes, temos:

$$
\left\{
\begin{array}{lcr}
 a'_{11} + 3a'_{21} = 1\\
 2a'_{11} + 7a'_{21} = 0\\
\end{array} 
\right. \implies a'_{11} = 7 \text{ e } a'_{21} = -2 \text{,}
$$

$$
\left\{
\begin{array}{lcr}
 a'_{12} + 3a'_{22} = 0\\
 2a'_{12} + 7a'_{22} = 1\\
\end{array} 
\right. \implies a'_{12} = -3 \text{ e } a'_{22} = 1 \text{.}
$$
Portanto,

$$
\mathbf{A}^{-1} = \begin{bmatrix}
7 & -3 \\ 
-2 & 1
\end{bmatrix} \text{.}
$$
Conforme visto em \@ref(matrices-operations), a divisão é uma operação não definida para matrizes, entretanto, a inversão serve para um propósito equivalente. Por exemplo, considere a seguinte expressão:

$$
\dfrac{b}{a} = \dfrac{1}{a} \cdot b = a^{-1}b \text{.}
$$

Observe que dividir $b$ por $a$ é o mesmo que multiplicar o inverso de $a$ por $b$. Portanto, sejam as matrizes

$$\mathbf{A} = \begin{bmatrix}
1 & 3 \\ 
2 & 7
\end{bmatrix} \text{ e } \mathbf{B} = \begin{bmatrix}
2 & 4 \\ 
6 & 8
\end{bmatrix} \text{,}
$$
se $\mathbf{A}$ é inversível, então o produto

$$
\mathbf{A}^{-1}\mathbf{B} = \begin{bmatrix}
-4 & 4 \\ 
2 & 0
\end{bmatrix}
$$
equivale à divisão de $\mathbf{B}$ por $\mathbf{A}$.

::: {.example}
Inversão de matrizes em Python.

Construindo as matrizes $\mathbf{A}$ e $\mathbf{B}$:

```{python}
import numpy as np

A = np.array([[1,3], [2,7]])
A

B = np.array([[2,4], [6,8]])
B
```

Obtendo a inversa $\mathbf{A}^{-1}$:

```{python}
np.linalg.inv(A)
```

Conferindo as expressões $\mathbf{A}\mathbf{A}^{-1} = \mathbf{I}$ e $\mathbf{A}^{-1}\mathbf{A} = \mathbf{I}$

```{python}
I = A @ np.linalg.inv(A)
I

I = np.linalg.inv(A) @ A
I
```

Calculando $\mathbf{A}^{-1} \mathbf{B}$:

```{python}
np.linalg.inv(A) @ B
```
:::
