# Matrizes

Matriz é uma tabela formada por números ou símbolos distribuídos em $n$ linhas e $m$ colunas. Por exemplo,

$$
\mathbf{A} = \begin{bmatrix}
4 & 2 & 1 \\ 
8 & 3 & 5
\end{bmatrix}
$$
é uma matriz $2 \times 3$ (lê-se "2 por 3" — 2 linhas e 3 colunas), e

$$\mathbf{B} = \begin{bmatrix}
7 & 0 \\ 
1 & -1 \\
11 & -3 \\
4 & 6
\end{bmatrix} \text{,}$$
uma matriz $4 \times 2$.

Os elementos de uma matriz são representados por $a_{ij}$, em que os índices $i$ e $j$ indicam a linha e a coluna às quais o elemento pertence, respectivamente. Por convenção, as linhas são numeradas de cima para baixo, com $i \in \{1,2,\ldots,n\}$, e as colunas, da esquerda para a direita, com $j \in \{1,2,\ldots,m\}$. Por exemplo,

$$
\mathbf{A} = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\ 
a_{21} & a_{22} & a_{23}
\end{bmatrix} \text{.}
$$
Cada elemento da matriz pode ser identificado por sua localizão exclusiva. Por exemplo, $a_{21}$ referencia o elemento da segunda linha e primeira coluna de $\mathbf{A}$, ou seja, $a_{21} = 8$.

Cada linha de uma matriz é uma matriz $1 \times m$. A linha 2 de $\mathbf{A}$, por exemplo, é uma matriz $1 \times 3$:

$$
\mathbf{L_2} = \begin{bmatrix}
8 & 3 & 5
\end{bmatrix} \text{.}
$$

E cada coluna de uma matriz é uma matriz $n \times 1$. Por exemplo, a coluna 1 de $\mathbf{B}$ é uma matriz $4 \times 1$:

$$
\mathbf{C_1} = \begin{bmatrix}
7 \\ 
1 \\
11 \\
4
\end{bmatrix} \text{.}
$$
Matrizes $1 \times m$ e $n \times 1$ também são conhecidas como vetores. Portanto, pode-se dizer que uma matriz $n \times m$ é composta por $n$ vetores linha ou $m$ vetores coluna.

::: {.example}
Primeiros passos com matrizes em Python.

Importante observar que na linguagem Python os índices sempre começam em 0. Ou seja, a linha ou coluna 1 da matriz é representada pelo índice 0 em Python, a linha ou coluna 2 pelo índice 1, e assim sucessivamente.

Construindo as matrizes $\mathbf{A}$ e $\mathbf{B}$:
```{python Intro}
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
A

B = np.array([[7,0], [1,-1], [11, -3], [4,6]])
B
```

Extraindo as dimensões de $\mathbf{A}$:
```{python}
n, m = A.shape
print(f'{n} linhas e {m} colunas')
```

Selecionando o elemento $a_{21}$ de $\mathbf{A}$:
```{python}
A[1,0]
```

Selecionando a linha 2 de $\mathbf{A}$:
```{python}
L2 = A[1,:]
L2
```

Selecionando a coluna 1 de $\mathbf{B}$:
```{python}
C1 = B[:,0]
C1
```
:::
